# -*- coding: utf-8 -*-
"""Fashion Visual Director Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ORqiR0q3IYV0xcpkRVuqZhVHLI8hfjox
"""

# visual_director_app.py
!pip install openai streamlit

import os
from datetime import datetime

import streamlit as st

# ── OpenAI SDK v1 방식 ─────────────────────────────────────────────
try:
    from openai import OpenAI
except ImportError:
    st.error("openai 패키지가 없습니다. 터미널에서 `pip install openai streamlit` 후 다시 실행하세요.")
    st.stop()

st.set_page_config(page_title="Fashion Visual Director Bot", layout="wide", page_icon="🎬")

# 사이드바: API Key & 설정
with st.sidebar:
    st.title("⚙️ 설정")
    OPENAI_API_KEY = st.text_input("OpenAI API Key", type="password", value=os.getenv("OPENAI_API_KEY", ""))
    model = st.selectbox("모델", ["gpt-4o-mini", "gpt-4o", "gpt-4.1-mini"])
    temperature = st.slider("Temperature", 0.0, 1.0, 0.6, 0.05)
    max_tokens = st.slider("Max tokens", 256, 4096, 1200, 64)
    st.caption("※ Key는 메모리에만 보관됩니다.")

st.title("🎬 패션 비주얼 디렉터 챗봇")

# 입력 폼
col1, col2 = st.columns(2)
with col1:
    project_name = st.text_input("프로젝트/컬렉션 이름", "Autumn Fragment")
    format_choice = st.selectbox("포맷", ["화보 (Editorial)", "런웨이 (Runway)", "온라인 룩북 (Lookbook)"])
    target = st.text_input("타깃 (예: 20-30대, K-fashion lovers 등)", "20-30대, 무드 중심 트렌드 소비자")
with col2:
    keywords = st.text_input("키워드/테마 (쉼표로 구분)", "deconstructivism, muted pastels")
    budget_note = st.text_input("예산/제약(선택)", "Low budget - student project")
user_prompt = st.text_area("디테일 요청", "원단의 질감과 디테일이 강조되는 스튜디오 화보. 자연광 느낌")

# 역할 프롬프트
system_prompt = """
너는 '패션 비주얼 디렉터'야.
사용자가 준 정보(프로젝트명, 포맷, 타깃, 키워드, 예산제약, 디테일)를 읽고 다음 항목을 출력해:
1) 핵심 콘셉트(한 문장)
2) 비주얼 디렉션: 조명/촬영스타일/구성/모델스타일/소품(각 항목 2-4가지)
3) 컬러 팔레트: 3~5개의 HEX 코드 및 간단한 설명
4) 텍스처/소재 추천(3개)
5) 샷리스트(3컷) - 각 컷의 구성과 목적
6) 예산/시간 제약 있을 때의 현실적인 변형 팁 (각 1-2개)
출력은 마크다운 형식으로 구성하고, 실무에서 바로 참고할 수 있게 구체적으로 작성해.
""".strip()

# 메시지 구성 함수
def build_messages():
    user_content = f"""
[프로젝트명] {project_name}
[포맷] {format_choice}
[타깃] {target}
[키워드/테마] {keywords}
[예산/제약] {budget_note}
[디테일 요청] {user_prompt}
""".strip()
    return [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_content},
    ]

# 실행 버튼
if st.button("✨ 제안 생성"):
    if not OPENAI_API_KEY:
        st.error("OpenAI API 키를 입력하세요 (사이드바).")
        st.stop()

    try:
        client = OpenAI(api_key=OPENAI_API_KEY)
        resp = client.chat.completions.create(
            model=model,
            messages=build_messages(),
            temperature=temperature,
            max_tokens=max_tokens,
        )
        text = resp.choices[0].message.content.strip()
        st.markdown("### 결과")
        st.markdown(text)

        # 선택: 간단 저장
        with st.expander("로그 저장하기"):
            if st.checkbox("현재 결과를 파일로 저장"):
                ts = datetime.now().strftime("%Y%m%d_%H%M%S")
                fname = f"{project_name}_{ts}.md"
                with open(fname, "w", encoding="utf-8") as f:
                    f.write(text)
                st.success(f"저장됨: {fname}")

    except Exception as e:
        st.error(f"API 호출 중 오류: {e}")