# -*- coding: utf-8 -*-
"""Fashion Visual Director Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ORqiR0q3IYV0xcpkRVuqZhVHLI8hfjox
"""

# visual_director_app.py
import streamlit as st
import openai
from datetime import datetime

st.set_page_config(page_title="Fashion Visual Director Bot", layout="wide", page_icon="🎬")

st.title("🎬 Fashion Visual Director Bot")
st.write("패션 비주얼 디렉터 역할로 콘셉트·무드보드·촬영지시를 제안합니다.")

# 1) API 키 로딩 (권장: Streamlit Cloud secrets 사용)
st.sidebar.header("API 설정")
use_secrets = st.sidebar.checkbox("Use Streamlit secrets (권장)", value=True)
if use_secrets:
    # Streamlit Cloud: Settings > Secrets에서 OPENAI_API_KEY 값 저장
    try:
        OPENAI_API_KEY = st.secrets["OPENAI_API_KEY"]
    except Exception:
        OPENAI_API_KEY = ""
else:
    OPENAI_API_KEY = st.sidebar.text_input("OpenAI API Key", type="password")

if not OPENAI_API_KEY:
    st.sidebar.warning("OpenAI API Key가 없습니다. 실행하려면 키 입력이 필요합니다.")

# 2) 사용자 입력
st.sidebar.header("옵션")
model = st.sidebar.text_input("Model (권장 예: gpt-4o-mini 또는 gpt-4o)", value="gpt-4o-mini")
temperature = st.sidebar.slider("창의성 (temperature)", 0.0, 1.0, 0.7)
max_tokens = st.sidebar.slider("Max tokens", 128, 2048, 512)

st.subheader("프로젝트 정보")
project_name = st.text_input("프로젝트/컬렉션 이름", "Autumn Fragment")
format_choice = st.selectbox("포맷", ["화보 (Editorial)", "런웨이 (Runway)", "온라인 룩북 (Lookbook)"])
target = st.text_input("타깃 (예: 20-30대, K-fashion lovers 등)", "20-30대, 무드 중심 트렌드 소비자")
keywords = st.text_input("키워드/테마 (쉼표로 구분 예: deconstructivism, muted pastels)", "deconstructivism, muted pastels")
budget_note = st.text_input("예산/제약(선택)", "Low budget - student project")

user_prompt = st.text_area("디테일 요청 (예: 촬영장소, 모델 콘셉트, 소품 등)",
                           "원단의 질감과 디테일이 강조되는 스튜디오 화보. 자연광 느낌")

# 3) System prompt (역할)
system_prompt = """
너는 '패션 비주얼 디렉터'야.
사용자가 준 정보(프로젝트명, 포맷, 타깃, 키워드, 예산제약, 디테일)를 읽고 다음 항목을 출력해:
1) 핵심 콘셉트(한 문장)
2) 비주얼 디렉션: 조명/촬영스타일/구성/모델스타일/소품(각 항목 2-4가지)
3) 컬러 팔레트: 3~5개의 HEX 코드 및 간단한 설명
4) 텍스처/소재 추천(3개)
5) 샷리스트(3컷) - 각 컷의 구성과 목적
6) 예산/시간 제약 있을 때의 현실적인 변형 팁 (각 1-2개)
출력은 마크다운 형식으로 구성하고, 실무에서 바로 참고할 수 있게 구체적으로 작성해.
"""

# 4) 실행 버튼
if st.button("제안 생성"):
    if not OPENAI_API_KEY:
        st.error("OpenAI API 키를 입력하세요 (사이드바).")
    else:
        openai.api_key = OPENAI_API_KEY

        system_msg = {"role": "system", "content": system_prompt}
        user_msg_text = f"""
Project: {project_name}
Format: {format_choice}
Target: {target}
Keywords: {keywords}
Budget note: {budget_note}
Detail: {user_prompt}
"""
        user_msg = {"role": "user", "content": user_msg_text}

        with st.spinner("디렉션 생성 중..."):
            try:
                resp = openai.ChatCompletion.create(
                    model=model,
                    messages=[system_msg, user_msg],
                    temperature=temperature,
                    max_tokens=max_tokens,
                )
                # ChatCompletion.response 구조에 따라 조정
                assistant_text = resp["choices"][0]["message"]["content"].strip()
                st.markdown("### ✨ 제안 결과")
                st.markdown(assistant_text)

                # 로그 저장(선택)
                if st.checkbox("대화 기록 저장"):
                    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
                    st.write(f"저장됨: {project_name}_{ts}")
                    # 실제 저장은 로컬/DB로 구현 가능 (예: st.download_button으로 다운로드 제공)
            except Exception as e:
                st.error(f"API 호출중 오류 발생: {e}")